modelsDir: "./models"
loraDir: "./loras"
outputDir: "./outputs"
modelName: "epicrealism_naturalSinRC1VAE.safetensors"
isLCMEnabled: "no"
isDetailerEnabled: "no"
imageNamePrefix: "Output"
inputYMLFile: "inputs.yml"
presetYMLFile: "presets_photography.yml"
scheduler: "dpm++_2m_karras"
isUpscalingEnabled: "no"